services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage # Name your container
    restart: unless-stopped
    ports:
      - 3000:3000 # Map host xxx port to container port 8080
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.x.x:3000 # Setting allowed ip
    volumes:
      - /your_path/homepage:/app/config # Mapping local config directory
      # (optional) For docker integrations
      # - /var/run/docker.sock:/var/run/docker.sock
