services:
  manynotes:
    image: brufdev/many-notes:latest
    container_name: manynotes
    restart: unless-stopped
    ports:
      - "5001:8080"
    user: "3000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=http://100.64.54.201:5001
      # Database configuration for MariaDB
      - DB_CONNECTION=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=manynotes
      - DB_USERNAME=${db_user}
      - DB_PASSWORD=${db_password}
      # SMTP configuration
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=${FROM_ADDRESS}
      - MAIL_FROM_NAME="Notatnik"
      # Path where Many Notes stores the actual Markdown files
      - APP_NOTES_PATH=/var/www/html/app/notes
    volumes:
      # Laravel logs
      - manynotes_logs:/var/www/html/storage/logs
      # Laravel internal private storage
      - manynotes_private:/var/www/html/storage/app/private
      # Map host path for actual Markdown notes files
      - /aplikacje/manynotes/markdown:/var/www/html/app/notes
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    container_name: manynotes_mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${db_root_password}
      - MARIADB_DATABASE=manynotes
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_password}
    volumes:
      - manynotes_db_data:/var/lib/mysql

volumes:
  manynotes_logs:
  manynotes_private:
  manynotes_db_data:
