services:
  nginx:
    image: nginx:latest
    ports:
      - "5002:80"
    volumes:
      - /website/webfiles:/var/www/html
      - /website/webconfig/default.conf:/etc/nginx/conf.d/default.conf #Create config file first
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - /website/webfiles:/var/www/html

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${rootpassword}
      MYSQL_DATABASE: ${mydb}
      MYSQL_USER: ${myuser}
      MYSQL_PASSWORD: ${mypass}
    volumes:
      - db_data:/var/lib/mysql

volumes:

  db_data:
